/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import framebuffer.FrameBuffer;

public class App {
    public static void main(String[] args) {
        FrameBuffer frameBuffer = new FrameBuffer("dummy_320x200");
    }
}
